# Generated by Django 5.2.1 on 2025-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='synopsis',
            field=models.CharField(default='hello'),
            preserve_default=False,
        ),
    ]
