# Generated by Django 5.2.4 on 2025-08-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
    ]
