# Generated by Django 5.2.4 on 2025-08-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_author_name_alter_publisher_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='prince',
            field=models.CharField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='last_sold',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
