# Generated by Django 5.2.4 on 2025-08-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_subject_prince_alter_book_last_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prince',
        ),
        migrations.AlterField(
            model_name='book',
            name='last_sold',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
    ]
