# Generated by Django 5.2.4 on 2025-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_remove_subject_prince_alter_book_last_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='last_sold',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
